apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8shello
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: springboot
          image: dwarak1262/k8shello:k8shello
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: k8shello
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8shello
